version: 2

defaults: &defaults
  working_directory: ~/project/vue-simple
  docker:
    - image: banian/node-headless-chrome

jobs:
  setup:
    <<: *defaults
    steps:
      #install expect
      - run:
        name: Install expect
        command: echo "y\r" | apt-get expect

  checkout:
    <<: *defaults
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "package.json" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      # Persist files
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-simple

  init:
    <<: *defaults
    steps:
      - run:
          name: Install Dependencies
          command: npm install -g vue-cli
      - run:
          name: Make sample
          command: expect .circleci/vue-init.exp
      - persist_to_workspace:
            root: ~/project/vue-simple
            paths:
              - sample

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - checkout

      - init:
        requires:
          - setup
          - checkout
