defaults: &defaults
  working_directory: ~/project/vue-simple
  docker:
    - image: circleci/node:8.10-browsers

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-simple

  init:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: apt update
          command: sudo apt-get update
      - run:
          name: Install expect
          command: sudo apt-get install -y expect && expect -v
      - run:
          name: Install vue-cli
          command: sudo npm install -g vue-cli && vue --version
      - run:
          name: Init vue template 'sample'
          command: expect .circleci/vue-cli-init.exp myproject mydescription "Real Name"
      - run:
          name: sample package.json
          working_directory: ~/project/vue-simple/sample
          command: cat package.json
      - run:
          name: Npm install
          working_directory: ~/project/vue-simple/sample
          command: npm install
      - run:
          name: Server start(npm run start)
          working_directory: ~/project/vue-simple/sample
          command: npm start
          background: true
      - run:
          name: GET index
          command: wget -O result.html --retry-connrefused --waitretry=2 --read-timeout=20 --timeout=15 -t 12 localhost:8080
      - run:
          name: Result response
          command: cat result.html

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - init:
          requires:
            - checkout
