version: 2

defaults: &defaults
  working_directory: ~/project/vue-simple
  docker:
    - image: circleci/node:8.10-browsers
     
jobs:
  setup:
    <<: *defaults
    steps:
      - run:
          name: Install expect
          command: sudo apt-get update; sudo apt-get install -y expect
      - run:
          name: Install vue-cli
          command: sudo npm install -g vue-cli

  checkout:
    <<: *defaults
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: package-{{ checksum "package-lock.json" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Keep cache
      - save_cache:
          key: package-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      # Persist files
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-simple

  init:
    <<: *defaults
    steps:
      - run:
          name: Make sample
          command: expect .circleci/vue-init.exp
      - persist_to_workspace:
            root: ~/project/vue-simple
            paths:
              - sample

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup

      - checkout:
          requires:
            - setup

      - init:
          requires:
            - setup
            - checkout
