defaults: &defaults
  working_directory: ~/project/vue-simple
  docker:
    - image: circleci/node:8.10-browsers


version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-simple

  init:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Default dependancies
          command: sudo apt-get update && sudo apt-get install -y expect && sudo npm install -g vue-cli
      - persist_to_workspace:
          root: ~/project/vue-simple
          paths:
            - .circleci
      - run:
          name: Init vue template 'sample'
          command: expect .circleci/vue-cli-init.exp myproject mydescription "Real Name"
      - run:
          working_directory: ~/project/vue-simple/sample
          name: root/sample package.json
          command: cat package.json
      - run:
          working_directory: ~/project/vue-simple/sample
          name: Npm install
          command: npm install
      - run:
          working_directory: ~/project/vue-simple/sample
          name: server run
          command: npm start
          background: true
      - run:
          name: response
          command: curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 60 'localhost:8080'

workflows:
  version: 2
  btd:
    jobs:
      - checkout
      - init:
          requires:
            - checkout
