version: 2

defaults: &defaults
  working_directory: ~/project/vue-simple
  docker:
    - image: banian/node-headless-chrome

jobs:
  checkout:
    <<: *defaults
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "package.json" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      # Persist files
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-simple

  init:
    <<: *defaults
    steps:
      - run:
          name: Install Dependencies
          command: npm install -g vue-cli
      - run:
          name: Install Dependencies
          command: vue init temping/vue-simple sample
      - persist_to_workspace:
            root: ~/project
            paths:
              - vue-simple/sample

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
  
      - init:
          requires:
            - checkout
