defaults: &defaults
  working_directory: ~/project/vue-simple
  docker:
    - image: circleci/node:8.10-browsers


version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      # Checkout repository
      - checkout

      # Persist files
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue-simple

  init:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Default dependancies
          command: sudo apt-get update && sudo apt-get install -y expect && sudo npm install -g vue-cli
      - persist_to_workspace:
          root: ~/project/vue-simple
          paths:
            - .circleci
      - run:
          name: Init vue template 'sample'
          command: expect .circleci/vue-cli-init.exp myproject mydescription "Real Name"
      - run:
          name: Check the root
          command: pwd && ls
      - run:
          name: Check the root/sample
          command: cd sample && pwd && ls
      - run:
          name: Npm install
          command: npm install

workflows:
  version: 2
  btd:
    jobs:
      - checkout
      - init:
          requires:
            - checkout
