#!/usr/bin/expect

# ./vue-cli-init.expect name desc auther

set timeout 120
set init_name [lindex $argv 0]
set init_description [lindex $argv 1]
set init_author [lindex $argv 2]

spawn vue init temping/vue-simple sample

expect {
  -re "App name" {
    send "$init_name\r"
    exp_continue
  }

  -re "description" {
    send "$init_name\r"
    exp_continue
  }

  -re "Author" {
    send "$init_name\r"
    exp_continue
  }
  
  timeout {
    exit 1
  }
}

expect eof